# Generated by Django 5.2.1 on 2025-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cefr_level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='key_sentences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='level_distribution',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='unique_words_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='vocabulary_size',
            field=models.IntegerField(default=0),
        ),
    ]
