# Generated by Django 5.2.1 on 2025-05-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_cefr_level_film_key_sentences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('cefr_level', models.CharField(max_length=2)),
                ('definition', models.TextField()),
                ('synonyms', models.JSONField(default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vocabularies',
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='vocabulary_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FilmVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=1)),
                ('first_occurrence', models.CharField(blank=True, max_length=200, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='films.film')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.vocabulary')),
            ],
            options={
                'verbose_name_plural': 'Film Vocabularies',
                'unique_together': {('film', 'vocabulary')},
            },
        ),
    ]
