# Generated by Django 5.2.1 on 2025-05-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_vocabulary_film_vocabulary_details_filmvocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image for the film', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_backdrop_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_homepage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_original_language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_original_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_poster_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_production_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_production_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_spoken_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
