# Generated by Django 5.2.1 on 2025-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_thumbnail_film_tmdb_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmvocabulary',
            name='context_sentences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='filmvocabulary',
            name='timestamps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='antonyms',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='difficulty_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='examples',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Mastery')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='filmvocabulary',
            index=models.Index(fields=['film', 'vocabulary'], name='films_filmv_film_id_86537a_idx'),
        ),
        migrations.AddIndex(
            model_name='filmvocabulary',
            index=models.Index(fields=['frequency'], name='films_filmv_frequen_243fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['word'], name='films_vocab_word_85060e_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['cefr_level'], name='films_vocab_cefr_le_ec0fea_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['usage_count'], name='films_vocab_usage_c_c66922_idx'),
        ),
    ]
