# Generated by Django 5.2.1 on 2025-06-03 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_film_requested_by_film_visibility_filmrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='film',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this film', related_name='allowed_films', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('requested', 'Requested')], default='requested', max_length=10),
        ),
    ]
