# Generated by Django 5.2.1 on 2025-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_remove_film_requested_by_film_allowed_users_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filmrequest',
            name='films_filmr_user_id_d7a7e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='filmrequest',
            name='films_filmr_tmdb_id_b10c62_idx',
        ),
        migrations.RemoveField(
            model_name='filmrequest',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmrequest',
            name='tmdb_overview',
        ),
        migrations.RemoveField(
            model_name='filmrequest',
            name='tmdb_poster_path',
        ),
        migrations.RemoveField(
            model_name='filmrequest',
            name='tmdb_title',
        ),
        migrations.AddField(
            model_name='filmrequest',
            name='title',
            field=models.CharField(default='Untitled Request', max_length=255),
        ),
        migrations.AlterField(
            model_name='filmrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='filmrequest',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
