# Generated by Django 5.2.1 on 2025-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='is_fast_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
