# Generated by Django 5.2.1 on 2025-06-06 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_filmwatch_film_estimated_delivery_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_payments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='filmrequest',
            name='completed_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='films.film'),
        ),
        migrations.AddField(
            model_name='filmrequest',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmrequest',
            name='is_fast_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filmrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filmrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_payments', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='film',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('requested', 'Requested'), ('processing', 'Processing'), ('ready', 'Ready')], default='requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='filmrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('processing', 'Processing'), ('ready', 'Ready')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='filmwatch',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='films.film'),
        ),
        migrations.AddField(
            model_name='filmwatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='filmwatch',
            index=models.Index(fields=['user', 'film'], name='films_filmw_user_id_1f63ab_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwatch',
            index=models.Index(fields=['watched_at'], name='films_filmw_watched_ef4483_idx'),
        ),
    ]
