# Generated by Django 5.2.1 on 2025-05-29 14:44

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_thumbnail_film_tmdb_backdrop_path_and_more'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_watched'], 'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture (max 5MB, JPG/PNG only)', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), profiles.models.validate_avatar_size], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography about the user', max_length=500, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this profile was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this profile was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='The user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='cefr_stats',
            field=models.JSONField(default=dict, help_text='Statistics for different CEFR levels', verbose_name='CEFR Statistics'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='film',
            field=models.ForeignKey(help_text='The film this progress is for', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='films.film', verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_watched',
            field=models.DateTimeField(auto_now=True, help_text='When the user last watched this film', verbose_name='Last Watched'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(help_text='The user this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='words_learned',
            field=models.JSONField(default=dict, help_text='Dictionary of learned words and their status', verbose_name='Words Learned'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='profiles_pr_created_b275ca_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['updated_at'], name='profiles_pr_updated_d17d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'film'], name='profiles_us_user_id_16f3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['last_watched'], name='profiles_us_last_wa_3c8bd4_idx'),
        ),
    ]
