# Generated by Django 5.2.1 on 2025-05-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_thumbnail_film_tmdb_backdrop_path_and_more'),
        ('profiles', '0002_alter_profile_options_alter_userprogress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.CreateModel(
            name='CEFRStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_count', models.PositiveIntegerField(default=0, help_text='Number of A1 level films watched', verbose_name='A1 Films')),
                ('a2_count', models.PositiveIntegerField(default=0, help_text='Number of A2 level films watched', verbose_name='A2 Films')),
                ('b1_count', models.PositiveIntegerField(default=0, help_text='Number of B1 level films watched', verbose_name='B1 Films')),
                ('b2_count', models.PositiveIntegerField(default=0, help_text='Number of B2 level films watched', verbose_name='B2 Films')),
                ('c1_count', models.PositiveIntegerField(default=0, help_text='Number of C1 level films watched', verbose_name='C1 Films')),
                ('c2_count', models.PositiveIntegerField(default=0, help_text='Number of C2 level films watched', verbose_name='C2 Films')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When these stats were last updated', verbose_name='Last Updated')),
                ('user', models.OneToOneField(help_text='The user these stats belong to', on_delete=django.db.models.deletion.CASCADE, related_name='cefr_stats', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'CEFR Statistics',
                'verbose_name_plural': 'CEFR Statistics',
            },
        ),
        migrations.CreateModel(
            name='WatchedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, help_text='When the film was watched', verbose_name='Watched At')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether this film is marked as favorite', verbose_name='Is Favorite')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], help_text='The CEFR level of the film', max_length=2, verbose_name='CEFR Level')),
                ('film', models.ForeignKey(help_text='The film that was watched', on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='films.film', verbose_name='Film')),
                ('user', models.ForeignKey(help_text='The user who watched the film', on_delete=django.db.models.deletion.CASCADE, related_name='watched_films', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Watched Film',
                'verbose_name_plural': 'Watched Films',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.AddIndex(
            model_name='cefrstats',
            index=models.Index(fields=['last_updated'], name='profiles_ce_last_up_4ce6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedfilm',
            index=models.Index(fields=['user', 'film'], name='profiles_wa_user_id_e575b4_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedfilm',
            index=models.Index(fields=['watched_at'], name='profiles_wa_watched_a20090_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedfilm',
            index=models.Index(fields=['cefr_level'], name='profiles_wa_cefr_le_b3c0f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchedfilm',
            unique_together={('user', 'film')},
        ),
    ]
