# Generated by Django 5.2.1 on 2025-05-21 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('zh', 'Chinese')], max_length=10)),
                ('sub_file', models.FileField(upload_to='subs/translated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_translations', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('film', 'language')},
            },
        ),
    ]
